# Generated by Django 6.1.1 on 2026-09-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('status', models.CharField(blank=True, help_text='e.g. "Full-Stack Project"', max_length=60)),
                ('description', models.TextField()),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars). Blank = auto from description.', max_length=160)),
                ('tech_stack', models.CharField(help_text='Comma separated, e.g. HTML, CSS, Django', max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='projects/%Y/%m/')),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
